---
Name: silverstripe-template-project
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: 'silverstripe-template-project'

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverstripeTemplateProject\SiteConfigExtension
