# Extend from current stable php apache
FROM php:7.3-apache

# Extra Repositories
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -

ENV LC_ALL C.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

# OS packages
RUN apt-get -y update; \
    apt-get -y upgrade;\
    apt-get install -f -y --no-install-recommends \
        apt-utils\
        ssl-cert \
        mariadb-client \
        zlib1g-dev \
        libicu-dev \
        libpng-dev \
        libjpeg-dev \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libwebp-dev \
        locales \
        gcc \
        g++ \
        gnupg \
        build-essential \
        zip \
        unzip \
        curl \
        git \
        ssh \
        jq \
        nano \
        vim \
        apt-utils \
        net-tools \
        iputils-ping \
        iproute2 \
        nodejs

RUN \
    # Installs SSPAK for SilverStripe
    # https://github.com/silverstripe/sspak
    curl -sS https://silverstripe.github.io/sspak/install | php -- /usr/local/bin; \
    # Composer binary
    curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/local/bin; \
    # Makes binaries specified by composer accessible to bash
    echo 'PATH=$PATH:/var/www/vendor/bin' >> /etc/bash.bashrc;

RUN \
    # Changes user id of www-data to 1000 for permissions and shares
    # compatibility with other machines
    usermod -u 1000 www-data; \
    groupmod -g 1000 www-data; \
    # Removes files we won't use from /var/www
    rm -rvf /var/www/*; \
    # Gives ownership of /var/solr to www-data to allow index creation
    mkdir /var/solr && chown -R www-data:www-data /var/solr; \
    mkdir /var/www/.npm && chown -R www-data:www-data /var/www/.npm; \
    mkdir -p /var/www/.composer/cache && chown -R www-data:www-data /var/www/.composer

# Installs PHP Extensions
RUN docker-php-ext-configure intl; \
    docker-php-ext-configure gd --with-png-dir=/usr/lib --with-jpeg-dir=/usr/lib --with-webp-dir=/usr/lib --with-freetype-dir=/usr/lib; \
    docker-php-ext-install -j$(nproc) intl \
        pdo_mysql \
        mysqli \
        gd \
        bcmath; \
    pecl install xdebug; \
    docker-php-ext-enable xdebug;

# Update npm and yarn
RUN npm install -g npm yarn

# Remove trash
RUN apt-get clean; \
    apt-get autoclean; \
    rm -r /var/lib/apt/lists/*

# PHP Configuration
COPY ["./dev/conf/php/php.ini", "/usr/local/etc/php/php.ini"]
COPY ["./dev/conf/php/docker-php-ext*", "/usr/local/etc/php/conf.d/"]

# Apache Configuration
COPY ["./dev/conf/apache2/docker.conf", "/etc/apache2/sites-enabled/000-default.conf"]
RUN \
    # Generates default SSL certificates
    make-ssl-cert generate-default-snakeoil; \
    # Generates SSL certificates for localhost
    cat /etc/ssl/openssl.cnf > /tmp/SSL_SAN_config; \
    printf "[SAN]\nsubjectAltName=DNS:localhost" >> /tmp/SSL_SAN_config; \
    openssl \
        req -newkey rsa:2048 -x509 -nodes \
        -keyout /etc/ssl/private/localhost.key \
        -new \
        -out /etc/ssl/certs/localhost.cert \
        -subj /CN=localhost \
        -reqexts SAN \
        -extensions SAN \
        -config /tmp/SSL_SAN_config \
        -sha256 -days 365; \
    # Adds both runtime users to the ssl-cert group
    usermod --append --groups ssl-cert root; \
    usermod --append --groups ssl-cert www-data;\
    # Enables apache modules
    a2enmod headers rewrite ssl

# Explicitly set the WORKDIR so that when we run drush commands via
# `docker-compose exec` they will work because the default working dir is the
# Drupal root dir.
WORKDIR /var/www

# Add the directory that composer will put tools such as phpunit, drupal
# console in to PATH so they are avaiable wihtout having to type the
# 'vendor/bin/' prefix
ENV PATH=$PATH:/var/www/vendor/bin

RUN echo 'export LS_OPTIONS="--color=auto"' >> /root/.bashrc
RUN echo 'alias ls="ls $LS_OPTIONS"' >> /root/.bashrc

# Give the www-data user a shell so that we can 'su' and 'sudo' to that user
RUN chsh -s /bin/bash www-data

RUN echo 'export LS_OPTIONS="--color=auto"' >> /var/www/.bashrc
RUN echo 'alias ls="ls $LS_OPTIONS"' >> /var/www/.bashrc

## Install SilverStripe

# Copy the composer files in so they are available for the 'composer install'
# command later in this file
COPY ["./composer.json", "/var/www/composer.json"]
COPY ["./composer.lock", "/var/www/composer.lock"]

# Copy the npm files in so they are available for the 'npm ci'
# command later in this file
COPY ["./package.json", "/var/www/package.json"]
COPY ["./package-lock.json", "/var/www/package-lock.json"]

# Copy public webroot. If this directory doesn't exist, the webroot will be
# assumed to be the current working directory when installing
COPY public /var/www/public

# Copy application files
COPY app /var/www/app

# Install application
RUN composer install --no-scripts
RUN composer vendor-expose
RUN npm ci

# Finally make the www-user own all files in /var/www
RUN chown -R www-data:www-data /var/www

# Remove the composer and npm files from the image because we will mount our own
# copies when we start the container. Removing the files should help avoid confusing
# situations where the old files are still around because we made an error with
# the volume mount.
RUN rm composer.json composer.lock package.json package-lock.json

ENTRYPOINT ["docker-php-entrypoint"]

EXPOSE 80
CMD ["apache2-foreground"]