#!/usr/bin/env bash

# Echo all commands just before they are executed
set -x

# Stop processing this script if any of the commands we run return an error
# (i.e. exit with a non-zero status)
set -e

cd /var/www

# Ensure we have the latest dependencies
composer install
npm ci

# Watch and compile
npm run watch
