#!/usr/bin/env bash

# Echo all commands just before they are executed
set -x

# Stop processing this script if any of the commands we run return an error
# (i.e. exit with a non-zero status)
set -e

cd /var/www

# We will be doing git operations from within this containers
domain=$(git ls-remote --get-url origin | cut -d'@' -f2 | cut -d':' -f1)
ssh-keyscan -t rsa $domain >> ~/.ssh/known_hosts

# Build a release version by merging `main` into this PR
git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git fetch origin
git checkout --track origin/deployment
git pull
git merge --no-commit --quiet main
