#!/usr/bin/env bash

# Echo all commands just before they are executed
set -x

# Stop processing this script if any of the commands we run return an error
# (i.e. exit with a non-zero status)
set -e

cd /var/www

# This script deploys our app to Heroku as a Dev environment
# CWP does not provide a DEV environment by default
git checkout ${BITBUCKET_TAG}
git pull
git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_ID.git HEAD:main
